[package]
authors = ["Maik Allgöwer <maik@llgoewer.de>"]
edition = "2021"
name = "aoc-2021"
version = "0.1.0"
[[bin]]
name = "aoc21-cli"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.50"
nom = "7.1.0"
pico-args = "0.4.2"

[lib]
name = "aoc21"
path = "src/lib.rs"
